// JavaScript Document
var ext2={
	"@type":"java.lang.RuntimeException",
	"cause":{
		"@type":"com.attilax.user.ex.UserExistEx",
		"cause":{
			"@type":"com.attilax.sql.ex.DuplicateEntryEx",
			"cause":{
				"@type":"java.sql.SQLException",
				"errorCode":1062,
				"localizedMessage":"Duplicate entry '7' for key 'uni_uid' Query: insert agent(uid,pwd)values('7','111111')  Parameters: []",
				"message":"Duplicate entry '7' for key 'uni_uid' Query: insert agent(uid,pwd)values('7','111111')  Parameters: []",
				"nextException":{
					"@type":"com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException",
					"errorCode":1062,
					"localizedMessage":"Duplicate entry '7' for key 'uni_uid'",
					"message":"Duplicate entry '7' for key 'uni_uid'",
					"sQLState":"23000",
					"stackTrace":[{
						"className":"sun.reflect.NativeConstructorAccessorImpl",
						"fileName":"NativeConstructorAccessorImpl.java",
						"lineNumber":-2,
						"methodName":"newInstance0",
						"nativeMethod":true
					},{
						"className":"sun.reflect.NativeConstructorAccessorImpl",
						"fileName":"NativeConstructorAccessorImpl.java",
						"lineNumber":62,
						"methodName":"newInstance",
						"nativeMethod":false
					},{
						"className":"sun.reflect.DelegatingConstructorAccessorImpl",
						"fileName":"DelegatingConstructorAccessorImpl.java",
						"lineNumber":45,
						"methodName":"newInstance",
						"nativeMethod":false
					},{
						"className":"java.lang.reflect.Constructor",
						"fileName":"Constructor.java",
						"lineNumber":422,
						"methodName":"newInstance",
						"nativeMethod":false
					},{
						"className":"com.mysql.jdbc.Util",
						"fileName":"Util.java",
						"lineNumber":406,
						"methodName":"handleNewInstance",
						"nativeMethod":false
					},{
						"className":"com.mysql.jdbc.Util",
						"fileName":"Util.java",
						"lineNumber":381,
						"methodName":"getInstance",
						"nativeMethod":false
					},{
						"className":"com.mysql.jdbc.SQLError",
						"fileName":"SQLError.java",
						"lineNumber":1015,
						"methodName":"createSQLException",
						"nativeMethod":false
					},{
						"className":"com.mysql.jdbc.SQLError",
						"fileName":"SQLError.java",
						"lineNumber":956,
						"methodName":"createSQLException",
						"nativeMethod":false
					},{
						"className":"com.mysql.jdbc.MysqlIO",
						"fileName":"MysqlIO.java",
						"lineNumber":3515,
						"methodName":"checkErrorPacket",
						"nativeMethod":false
					},{
						"className":"com.mysql.jdbc.MysqlIO",
						"fileName":"MysqlIO.java",
						"lineNumber":3447,
						"methodName":"checkErrorPacket",
						"nativeMethod":false
					},{
						"className":"com.mysql.jdbc.MysqlIO",
						"fileName":"MysqlIO.java",
						"lineNumber":1951,
						"methodName":"sendCommand",
						"nativeMethod":false
					},{
						"className":"com.mysql.jdbc.MysqlIO",
						"fileName":"MysqlIO.java",
						"lineNumber":2101,
						"methodName":"sqlQueryDirect",
						"nativeMethod":false
					},{
						"className":"com.mysql.jdbc.ConnectionImpl",
						"fileName":"ConnectionImpl.java",
						"lineNumber":2554,
						"methodName":"execSQL",
						"nativeMethod":false
					},{
						"className":"com.mysql.jdbc.PreparedStatement",
						"fileName":"PreparedStatement.java",
						"lineNumber":1761,
						"methodName":"executeInternal",
						"nativeMethod":false
					},{
						"className":"com.mysql.jdbc.PreparedStatement",
						"fileName":"PreparedStatement.java",
						"lineNumber":2046,
						"methodName":"executeUpdate",
						"nativeMethod":false
					},{
						"className":"com.mysql.jdbc.PreparedStatement",
						"fileName":"PreparedStatement.java",
						"lineNumber":1964,
						"methodName":"executeUpdate",
						"nativeMethod":false
					},{
						"className":"com.mysql.jdbc.PreparedStatement",
						"fileName":"PreparedStatement.java",
						"lineNumber":1949,
						"methodName":"executeUpdate",
						"nativeMethod":false
					},{
						"className":"org.apache.commons.dbutils.QueryRunner",
						"fileName":"QueryRunner.java",
						"lineNumber":488,
						"methodName":"update",
						"nativeMethod":false
					},{
						"className":"org.apache.commons.dbutils.QueryRunner",
						"fileName":"QueryRunner.java",
						"lineNumber":377,
						"methodName":"update",
						"nativeMethod":false
					},{
						"className":"com.attilax.db.DbServiceV4qb9",
						"fileName":"DbServiceV4qb9.java",
						"lineNumber":232,
						"methodName":"executeUpdateV2qb0",
						"nativeMethod":false
					},{
						"className":"com.attilax.user.AgentService",
						"fileName":"AgentService.java",
						"lineNumber":273,
						"methodName":"setSubHiagt4adm",
						"nativeMethod":false
					},{
						"className":"sun.reflect.NativeMethodAccessorImpl",
						"fileName":"NativeMethodAccessorImpl.java",
						"lineNumber":-2,
						"methodName":"invoke0",
						"nativeMethod":true
					},{
						"className":"sun.reflect.NativeMethodAccessorImpl",
						"fileName":"NativeMethodAccessorImpl.java",
						"lineNumber":62,
						"methodName":"invoke",
						"nativeMethod":false
					},{
						"className":"sun.reflect.DelegatingMethodAccessorImpl",
						"fileName":"DelegatingMethodAccessorImpl.java",
						"lineNumber":43,
						"methodName":"invoke",
						"nativeMethod":false
					},{
						"className":"java.lang.reflect.Method",
						"fileName":"Method.java",
						"lineNumber":497,
						"methodName":"invoke",
						"nativeMethod":false
					},{
						"className":"org.apache.commons.lang3.reflect.MethodUtils",
						"fileName":"MethodUtils.java",
						"lineNumber":133,
						"methodName":"invokeMethod",
						"nativeMethod":false
					},{
						"className":"org.apache.commons.lang3.reflect.MethodUtils",
						"fileName":"MethodUtils.java",
						"lineNumber":94,
						"methodName":"invokeMethod",
						"nativeMethod":false
					},{
						"className":"com.attilax.lang.Exprs",
						"fileName":"Exprs.java",
						"lineNumber":91,
						"methodName":"calc",
						"nativeMethod":false
					},{
						"className":"com.attilax.lang.AstParser",
						"fileName":"AstParser.java",
						"lineNumber":58,
						"methodName":"parseSingle",
						"nativeMethod":false
					},{
						"className":"com.attilax.lang.AstParser",
						"fileName":"AstParser.java",
						"lineNumber":49,
						"methodName":"parse",
						"nativeMethod":false
					},{
						"className":"com.attilax.wrmi.wrmiServletV3",
						"fileName":"wrmiServletV3.java",
						"lineNumber":157,
						"methodName":"service",
						"nativeMethod":false
					},{
						"className":"com.caucho.server.dispatch.ServletFilterChain",
						"fileName":"ServletFilterChain.java",
						"lineNumber":109,
						"methodName":"doFilter",
						"nativeMethod":false
					},{
						"className":"com.attilax.lang.exCatchor",
						"fileName":"exCatchor.java",
						"lineNumber":55,
						"methodName":"doFilter",
						"nativeMethod":false
					},{
						"className":"com.caucho.server.dispatch.FilterFilterChain",
						"fileName":"FilterFilterChain.java",
						"lineNumber":89,
						"methodName":"doFilter",
						"nativeMethod":false
					},{
						"className":"com.attilax.corePkg.ChineseCharFileUrlFilter",
						"fileName":"ChineseCharFileUrlFilter.java",
						"lineNumber":95,
						"methodName":"doFilter",
						"nativeMethod":false
					},{
						"className":"com.caucho.server.dispatch.FilterFilterChain",
						"fileName":"FilterFilterChain.java",
						"lineNumber":89,
						"methodName":"doFilter",
						"nativeMethod":false
					},{
						"className":"org.springframework.web.filter.CharacterEncodingFilter",
						"fileName":"CharacterEncodingFilter.java",
						"lineNumber":96,
						"methodName":"doFilterInternal",
						"nativeMethod":false
					},{
						"className":"org.springframework.web.filter.OncePerRequestFilter",
						"fileName":"OncePerRequestFilter.java",
						"lineNumber":76,
						"methodName":"doFilter",
						"nativeMethod":false
					},{
						"className":"com.caucho.server.dispatch.FilterFilterChain",
						"fileName":"FilterFilterChain.java",
						"lineNumber":89,
						"methodName":"doFilter",
						"nativeMethod":false
					},{
						"className":"com.caucho.server.webapp.WebAppFilterChain",
						"fileName":"WebAppFilterChain.java",
						"lineNumber":156,
						"methodName":"doFilter",
						"nativeMethod":false
					},{
						"className":"com.caucho.server.webapp.AccessLogFilterChain",
						"fileName":"AccessLogFilterChain.java",
						"lineNumber":95,
						"methodName":"doFilter",
						"nativeMethod":false
					},{
						"className":"com.caucho.server.dispatch.ServletInvocation",
						"fileName":"ServletInvocation.java",
						"lineNumber":289,
						"methodName":"service",
						"nativeMethod":false
					},{
						"className":"com.caucho.server.http.HttpRequest",
						"fileName":"HttpRequest.java",
						"lineNumber":811,
						"methodName":"handleRequest",
						"nativeMethod":false
					},{
						"className":"com.caucho.network.listen.TcpSocketLink",
						"fileName":"TcpSocketLink.java",
						"lineNumber":1203,
						"methodName":"dispatchRequest",
						"nativeMethod":false
					},{
						"className":"com.caucho.network.listen.TcpSocketLink",
						"fileName":"TcpSocketLink.java",
						"lineNumber":1164,
						"methodName":"handleRequest",
						"nativeMethod":false
					},{
						"className":"com.caucho.network.listen.TcpSocketLink",
						"fileName":"TcpSocketLink.java",
						"lineNumber":1148,
						"methodName":"handleRequestsImpl",
						"nativeMethod":false
					},{
						"className":"com.caucho.network.listen.TcpSocketLink",
						"fileName":"TcpSocketLink.java",
						"lineNumber":1071,
						"methodName":"handleRequests",
						"nativeMethod":false
					},{
						"className":"com.caucho.network.listen.TcpSocketLink",
						"fileName":"TcpSocketLink.java",
						"lineNumber":907,
						"methodName":"handleAcceptTask",
						"nativeMethod":false
					},{
						"className":"com.caucho.network.listen.AcceptTask",
						"fileName":"AcceptTask.java",
						"lineNumber":74,
						"methodName":"doTask",
						"nativeMethod":false
					},{
						"className":"com.caucho.network.listen.ConnectionTask",
						"fileName":"ConnectionTask.java",
						"lineNumber":97,
						"methodName":"runThread",
						"nativeMethod":false
					},{
						"className":"com.caucho.network.listen.ConnectionTask",
						"fileName":"ConnectionTask.java",
						"lineNumber":80,
						"methodName":"run",
						"nativeMethod":false
					},{
						"className":"com.caucho.network.listen.AcceptTask",
						"fileName":"AcceptTask.java",
						"lineNumber":59,
						"methodName":"run",
						"nativeMethod":false
					},{
						"className":"com.caucho.env.thread.ResinThread",
						"fileName":"ResinThread.java",
						"lineNumber":164,
						"methodName":"runTasks",
						"nativeMethod":false
					},{
						"className":"com.caucho.env.thread.ResinThread",
						"fileName":"ResinThread.java",
						"lineNumber":130,
						"methodName":"run",
						"nativeMethod":false
					}],
					"suppressed":[]
				},
				"sQLState":"23000",
				"stackTrace":[{
					"className":"org.apache.commons.dbutils.AbstractQueryRunner",
					"fileName":"AbstractQueryRunner.java",
					"lineNumber":392,
					"methodName":"rethrow",
					"nativeMethod":false
				},{
					"className":"org.apache.commons.dbutils.QueryRunner",
					"fileName":"QueryRunner.java",
					"lineNumber":491,
					"methodName":"update",
					"nativeMethod":false
				},{
					"className":"org.apache.commons.dbutils.QueryRunner",
					"fileName":"QueryRunner.java",
					"lineNumber":377,
					"methodName":"update",
					"nativeMethod":false
				},{
					"className":"com.attilax.db.DbServiceV4qb9",
					"fileName":"DbServiceV4qb9.java",
					"lineNumber":232,
					"methodName":"executeUpdateV2qb0",
					"nativeMethod":false
				},{
					"className":"com.attilax.user.AgentService",
					"fileName":"AgentService.java",
					"lineNumber":273,
					"methodName":"setSubHiagt4adm",
					"nativeMethod":false
				},{
					"className":"sun.reflect.NativeMethodAccessorImpl",
					"fileName":"NativeMethodAccessorImpl.java",
					"lineNumber":-2,
					"methodName":"invoke0",
					"nativeMethod":true
				},{
					"className":"sun.reflect.NativeMethodAccessorImpl",
					"fileName":"NativeMethodAccessorImpl.java",
					"lineNumber":62,
					"methodName":"invoke",
					"nativeMethod":false
				},{
					"className":"sun.reflect.DelegatingMethodAccessorImpl",
					"fileName":"DelegatingMethodAccessorImpl.java",
					"lineNumber":43,
					"methodName":"invoke",
					"nativeMethod":false
				},{
					"className":"java.lang.reflect.Method",
					"fileName":"Method.java",
					"lineNumber":497,
					"methodName":"invoke",
					"nativeMethod":false
				},{
					"className":"org.apache.commons.lang3.reflect.MethodUtils",
					"fileName":"MethodUtils.java",
					"lineNumber":133,
					"methodName":"invokeMethod",
					"nativeMethod":false
				},{
					"className":"org.apache.commons.lang3.reflect.MethodUtils",
					"fileName":"MethodUtils.java",
					"lineNumber":94,
					"methodName":"invokeMethod",
					"nativeMethod":false
				},{
					"className":"com.attilax.lang.Exprs",
					"fileName":"Exprs.java",
					"lineNumber":91,
					"methodName":"calc",
					"nativeMethod":false
				},{
					"className":"com.attilax.lang.AstParser",
					"fileName":"AstParser.java",
					"lineNumber":58,
					"methodName":"parseSingle",
					"nativeMethod":false
				},{
					"className":"com.attilax.lang.AstParser",
					"fileName":"AstParser.java",
					"lineNumber":49,
					"methodName":"parse",
					"nativeMethod":false
				},{
					"className":"com.attilax.wrmi.wrmiServletV3",
					"fileName":"wrmiServletV3.java",
					"lineNumber":157,
					"methodName":"service",
					"nativeMethod":false
				},{
					"className":"com.caucho.server.dispatch.ServletFilterChain",
					"fileName":"ServletFilterChain.java",
					"lineNumber":109,
					"methodName":"doFilter",
					"nativeMethod":false
				},{
					"className":"com.attilax.lang.exCatchor",
					"fileName":"exCatchor.java",
					"lineNumber":55,
					"methodName":"doFilter",
					"nativeMethod":false
				},{
					"className":"com.caucho.server.dispatch.FilterFilterChain",
					"fileName":"FilterFilterChain.java",
					"lineNumber":89,
					"methodName":"doFilter",
					"nativeMethod":false
				},{
					"className":"com.attilax.corePkg.ChineseCharFileUrlFilter",
					"fileName":"ChineseCharFileUrlFilter.java",
					"lineNumber":95,
					"methodName":"doFilter",
					"nativeMethod":false
				},{
					"className":"com.caucho.server.dispatch.FilterFilterChain",
					"fileName":"FilterFilterChain.java",
					"lineNumber":89,
					"methodName":"doFilter",
					"nativeMethod":false
				},{
					"className":"org.springframework.web.filter.CharacterEncodingFilter",
					"fileName":"CharacterEncodingFilter.java",
					"lineNumber":96,
					"methodName":"doFilterInternal",
					"nativeMethod":false
				},{
					"className":"org.springframework.web.filter.OncePerRequestFilter",
					"fileName":"OncePerRequestFilter.java",
					"lineNumber":76,
					"methodName":"doFilter",
					"nativeMethod":false
				},{
					"className":"com.caucho.server.dispatch.FilterFilterChain",
					"fileName":"FilterFilterChain.java",
					"lineNumber":89,
					"methodName":"doFilter",
					"nativeMethod":false
				},{
					"className":"com.caucho.server.webapp.WebAppFilterChain",
					"fileName":"WebAppFilterChain.java",
					"lineNumber":156,
					"methodName":"doFilter",
					"nativeMethod":false
				},{
					"className":"com.caucho.server.webapp.AccessLogFilterChain",
					"fileName":"AccessLogFilterChain.java",
					"lineNumber":95,
					"methodName":"doFilter",
					"nativeMethod":false
				},{
					"className":"com.caucho.server.dispatch.ServletInvocation",
					"fileName":"ServletInvocation.java",
					"lineNumber":289,
					"methodName":"service",
					"nativeMethod":false
				},{
					"className":"com.caucho.server.http.HttpRequest",
					"fileName":"HttpRequest.java",
					"lineNumber":811,
					"methodName":"handleRequest",
					"nativeMethod":false
				},{
					"className":"com.caucho.network.listen.TcpSocketLink",
					"fileName":"TcpSocketLink.java",
					"lineNumber":1203,
					"methodName":"dispatchRequest",
					"nativeMethod":false
				},{
					"className":"com.caucho.network.listen.TcpSocketLink",
					"fileName":"TcpSocketLink.java",
					"lineNumber":1164,
					"methodName":"handleRequest",
					"nativeMethod":false
				},{
					"className":"com.caucho.network.listen.TcpSocketLink",
					"fileName":"TcpSocketLink.java",
					"lineNumber":1148,
					"methodName":"handleRequestsImpl",
					"nativeMethod":false
				},{
					"className":"com.caucho.network.listen.TcpSocketLink",
					"fileName":"TcpSocketLink.java",
					"lineNumber":1071,
					"methodName":"handleRequests",
					"nativeMethod":false
				},{
					"className":"com.caucho.network.listen.TcpSocketLink",
					"fileName":"TcpSocketLink.java",
					"lineNumber":907,
					"methodName":"handleAcceptTask",
					"nativeMethod":false
				},{
					"className":"com.caucho.network.listen.AcceptTask",
					"fileName":"AcceptTask.java",
					"lineNumber":74,
					"methodName":"doTask",
					"nativeMethod":false
				},{
					"className":"com.caucho.network.listen.ConnectionTask",
					"fileName":"ConnectionTask.java",
					"lineNumber":97,
					"methodName":"runThread",
					"nativeMethod":false
				},{
					"className":"com.caucho.network.listen.ConnectionTask",
					"fileName":"ConnectionTask.java",
					"lineNumber":80,
					"methodName":"run",
					"nativeMethod":false
				},{
					"className":"com.caucho.network.listen.AcceptTask",
					"fileName":"AcceptTask.java",
					"lineNumber":59,
					"methodName":"run",
					"nativeMethod":false
				},{
					"className":"com.caucho.env.thread.ResinThread",
					"fileName":"ResinThread.java",
					"lineNumber":164,
					"methodName":"runTasks",
					"nativeMethod":false
				},{
					"className":"com.caucho.env.thread.ResinThread",
					"fileName":"ResinThread.java",
					"lineNumber":130,
					"methodName":"run",
					"nativeMethod":false
				}],
				"suppressed":[]
			},
			"localizedMessage":"Duplicate entry '7' for key 'uni_uid' Query: insert agent(uid,pwd)values('7','111111')  Parameters: []",
			"message":"Duplicate entry '7' for key 'uni_uid' Query: insert agent(uid,pwd)values('7','111111')  Parameters: []",
			"stackTrace":[{
				"className":"com.attilax.db.DbServiceV4qb9",
				"fileName":"DbServiceV4qb9.java",
				"lineNumber":236,
				"methodName":"executeUpdateV2qb0",
				"nativeMethod":false
			},{
				"className":"com.attilax.user.AgentService",
				"fileName":"AgentService.java",
				"lineNumber":273,
				"methodName":"setSubHiagt4adm",
				"nativeMethod":false
			},{
				"className":"sun.reflect.NativeMethodAccessorImpl",
				"fileName":"NativeMethodAccessorImpl.java",
				"lineNumber":-2,
				"methodName":"invoke0",
				"nativeMethod":true
			},{
				"className":"sun.reflect.NativeMethodAccessorImpl",
				"fileName":"NativeMethodAccessorImpl.java",
				"lineNumber":62,
				"methodName":"invoke",
				"nativeMethod":false
			},{
				"className":"sun.reflect.DelegatingMethodAccessorImpl",
				"fileName":"DelegatingMethodAccessorImpl.java",
				"lineNumber":43,
				"methodName":"invoke",
				"nativeMethod":false
			},{
				"className":"java.lang.reflect.Method",
				"fileName":"Method.java",
				"lineNumber":497,
				"methodName":"invoke",
				"nativeMethod":false
			},{
				"className":"org.apache.commons.lang3.reflect.MethodUtils",
				"fileName":"MethodUtils.java",
				"lineNumber":133,
				"methodName":"invokeMethod",
				"nativeMethod":false
			},{
				"className":"org.apache.commons.lang3.reflect.MethodUtils",
				"fileName":"MethodUtils.java",
				"lineNumber":94,
				"methodName":"invokeMethod",
				"nativeMethod":false
			},{
				"className":"com.attilax.lang.Exprs",
				"fileName":"Exprs.java",
				"lineNumber":91,
				"methodName":"calc",
				"nativeMethod":false
			},{
				"className":"com.attilax.lang.AstParser",
				"fileName":"AstParser.java",
				"lineNumber":58,
				"methodName":"parseSingle",
				"nativeMethod":false
			},{
				"className":"com.attilax.lang.AstParser",
				"fileName":"AstParser.java",
				"lineNumber":49,
				"methodName":"parse",
				"nativeMethod":false
			},{
				"className":"com.attilax.wrmi.wrmiServletV3",
				"fileName":"wrmiServletV3.java",
				"lineNumber":157,
				"methodName":"service",
				"nativeMethod":false
			},{
				"className":"com.caucho.server.dispatch.ServletFilterChain",
				"fileName":"ServletFilterChain.java",
				"lineNumber":109,
				"methodName":"doFilter",
				"nativeMethod":false
			},{
				"className":"com.attilax.lang.exCatchor",
				"fileName":"exCatchor.java",
				"lineNumber":55,
				"methodName":"doFilter",
				"nativeMethod":false
			},{
				"className":"com.caucho.server.dispatch.FilterFilterChain",
				"fileName":"FilterFilterChain.java",
				"lineNumber":89,
				"methodName":"doFilter",
				"nativeMethod":false
			},{
				"className":"com.attilax.corePkg.ChineseCharFileUrlFilter",
				"fileName":"ChineseCharFileUrlFilter.java",
				"lineNumber":95,
				"methodName":"doFilter",
				"nativeMethod":false
			},{
				"className":"com.caucho.server.dispatch.FilterFilterChain",
				"fileName":"FilterFilterChain.java",
				"lineNumber":89,
				"methodName":"doFilter",
				"nativeMethod":false
			},{
				"className":"org.springframework.web.filter.CharacterEncodingFilter",
				"fileName":"CharacterEncodingFilter.java",
				"lineNumber":96,
				"methodName":"doFilterInternal",
				"nativeMethod":false
			},{
				"className":"org.springframework.web.filter.OncePerRequestFilter",
				"fileName":"OncePerRequestFilter.java",
				"lineNumber":76,
				"methodName":"doFilter",
				"nativeMethod":false
			},{
				"className":"com.caucho.server.dispatch.FilterFilterChain",
				"fileName":"FilterFilterChain.java",
				"lineNumber":89,
				"methodName":"doFilter",
				"nativeMethod":false
			},{
				"className":"com.caucho.server.webapp.WebAppFilterChain",
				"fileName":"WebAppFilterChain.java",
				"lineNumber":156,
				"methodName":"doFilter",
				"nativeMethod":false
			},{
				"className":"com.caucho.server.webapp.AccessLogFilterChain",
				"fileName":"AccessLogFilterChain.java",
				"lineNumber":95,
				"methodName":"doFilter",
				"nativeMethod":false
			},{
				"className":"com.caucho.server.dispatch.ServletInvocation",
				"fileName":"ServletInvocation.java",
				"lineNumber":289,
				"methodName":"service",
				"nativeMethod":false
			},{
				"className":"com.caucho.server.http.HttpRequest",
				"fileName":"HttpRequest.java",
				"lineNumber":811,
				"methodName":"handleRequest",
				"nativeMethod":false
			},{
				"className":"com.caucho.network.listen.TcpSocketLink",
				"fileName":"TcpSocketLink.java",
				"lineNumber":1203,
				"methodName":"dispatchRequest",
				"nativeMethod":false
			},{
				"className":"com.caucho.network.listen.TcpSocketLink",
				"fileName":"TcpSocketLink.java",
				"lineNumber":1164,
				"methodName":"handleRequest",
				"nativeMethod":false
			},{
				"className":"com.caucho.network.listen.TcpSocketLink",
				"fileName":"TcpSocketLink.java",
				"lineNumber":1148,
				"methodName":"handleRequestsImpl",
				"nativeMethod":false
			},{
				"className":"com.caucho.network.listen.TcpSocketLink",
				"fileName":"TcpSocketLink.java",
				"lineNumber":1071,
				"methodName":"handleRequests",
				"nativeMethod":false
			},{
				"className":"com.caucho.network.listen.TcpSocketLink",
				"fileName":"TcpSocketLink.java",
				"lineNumber":907,
				"methodName":"handleAcceptTask",
				"nativeMethod":false
			},{
				"className":"com.caucho.network.listen.AcceptTask",
				"fileName":"AcceptTask.java",
				"lineNumber":74,
				"methodName":"doTask",
				"nativeMethod":false
			},{
				"className":"com.caucho.network.listen.ConnectionTask",
				"fileName":"ConnectionTask.java",
				"lineNumber":97,
				"methodName":"runThread",
				"nativeMethod":false
			},{
				"className":"com.caucho.network.listen.ConnectionTask",
				"fileName":"ConnectionTask.java",
				"lineNumber":80,
				"methodName":"run",
				"nativeMethod":false
			},{
				"className":"com.caucho.network.listen.AcceptTask",
				"fileName":"AcceptTask.java",
				"lineNumber":59,
				"methodName":"run",
				"nativeMethod":false
			},{
				"className":"com.caucho.env.thread.ResinThread",
				"fileName":"ResinThread.java",
				"lineNumber":164,
				"methodName":"runTasks",
				"nativeMethod":false
			},{
				"className":"com.caucho.env.thread.ResinThread",
				"fileName":"ResinThread.java",
				"lineNumber":130,
				"methodName":"run",
				"nativeMethod":false
			}],
			"suppressed":[]
		},
		"localizedMessage":"Duplicate entry '7' for key 'uni_uid' Query: insert agent(uid,pwd)values('7','111111')  Parameters: []",
		"message":"Duplicate entry '7' for key 'uni_uid' Query: insert agent(uid,pwd)values('7','111111')  Parameters: []",
		"stackTrace":[{
			"className":"com.attilax.user.AgentService",
			"fileName":"AgentService.java",
			"lineNumber":275,
			"methodName":"setSubHiagt4adm",
			"nativeMethod":false
		},{
			"className":"sun.reflect.NativeMethodAccessorImpl",
			"fileName":"NativeMethodAccessorImpl.java",
			"lineNumber":-2,
			"methodName":"invoke0",
			"nativeMethod":true
		},{
			"className":"sun.reflect.NativeMethodAccessorImpl",
			"fileName":"NativeMethodAccessorImpl.java",
			"lineNumber":62,
			"methodName":"invoke",
			"nativeMethod":false
		},{
			"className":"sun.reflect.DelegatingMethodAccessorImpl",
			"fileName":"DelegatingMethodAccessorImpl.java",
			"lineNumber":43,
			"methodName":"invoke",
			"nativeMethod":false
		},{
			"className":"java.lang.reflect.Method",
			"fileName":"Method.java",
			"lineNumber":497,
			"methodName":"invoke",
			"nativeMethod":false
		},{
			"className":"org.apache.commons.lang3.reflect.MethodUtils",
			"fileName":"MethodUtils.java",
			"lineNumber":133,
			"methodName":"invokeMethod",
			"nativeMethod":false
		},{
			"className":"org.apache.commons.lang3.reflect.MethodUtils",
			"fileName":"MethodUtils.java",
			"lineNumber":94,
			"methodName":"invokeMethod",
			"nativeMethod":false
		},{
			"className":"com.attilax.lang.Exprs",
			"fileName":"Exprs.java",
			"lineNumber":91,
			"methodName":"calc",
			"nativeMethod":false
		},{
			"className":"com.attilax.lang.AstParser",
			"fileName":"AstParser.java",
			"lineNumber":58,
			"methodName":"parseSingle",
			"nativeMethod":false
		},{
			"className":"com.attilax.lang.AstParser",
			"fileName":"AstParser.java",
			"lineNumber":49,
			"methodName":"parse",
			"nativeMethod":false
		},{
			"className":"com.attilax.wrmi.wrmiServletV3",
			"fileName":"wrmiServletV3.java",
			"lineNumber":157,
			"methodName":"service",
			"nativeMethod":false
		},{
			"className":"com.caucho.server.dispatch.ServletFilterChain",
			"fileName":"ServletFilterChain.java",
			"lineNumber":109,
			"methodName":"doFilter",
			"nativeMethod":false
		},{
			"className":"com.attilax.lang.exCatchor",
			"fileName":"exCatchor.java",
			"lineNumber":55,
			"methodName":"doFilter",
			"nativeMethod":false
		},{
			"className":"com.caucho.server.dispatch.FilterFilterChain",
			"fileName":"FilterFilterChain.java",
			"lineNumber":89,
			"methodName":"doFilter",
			"nativeMethod":false
		},{
			"className":"com.attilax.corePkg.ChineseCharFileUrlFilter",
			"fileName":"ChineseCharFileUrlFilter.java",
			"lineNumber":95,
			"methodName":"doFilter",
			"nativeMethod":false
		},{
			"className":"com.caucho.server.dispatch.FilterFilterChain",
			"fileName":"FilterFilterChain.java",
			"lineNumber":89,
			"methodName":"doFilter",
			"nativeMethod":false
		},{
			"className":"org.springframework.web.filter.CharacterEncodingFilter",
			"fileName":"CharacterEncodingFilter.java",
			"lineNumber":96,
			"methodName":"doFilterInternal",
			"nativeMethod":false
		},{
			"className":"org.springframework.web.filter.OncePerRequestFilter",
			"fileName":"OncePerRequestFilter.java",
			"lineNumber":76,
			"methodName":"doFilter",
			"nativeMethod":false
		},{
			"className":"com.caucho.server.dispatch.FilterFilterChain",
			"fileName":"FilterFilterChain.java",
			"lineNumber":89,
			"methodName":"doFilter",
			"nativeMethod":false
		},{
			"className":"com.caucho.server.webapp.WebAppFilterChain",
			"fileName":"WebAppFilterChain.java",
			"lineNumber":156,
			"methodName":"doFilter",
			"nativeMethod":false
		},{
			"className":"com.caucho.server.webapp.AccessLogFilterChain",
			"fileName":"AccessLogFilterChain.java",
			"lineNumber":95,
			"methodName":"doFilter",
			"nativeMethod":false
		},{
			"className":"com.caucho.server.dispatch.ServletInvocation",
			"fileName":"ServletInvocation.java",
			"lineNumber":289,
			"methodName":"service",
			"nativeMethod":false
		},{
			"className":"com.caucho.server.http.HttpRequest",
			"fileName":"HttpRequest.java",
			"lineNumber":811,
			"methodName":"handleRequest",
			"nativeMethod":false
		},{
			"className":"com.caucho.network.listen.TcpSocketLink",
			"fileName":"TcpSocketLink.java",
			"lineNumber":1203,
			"methodName":"dispatchRequest",
			"nativeMethod":false
		},{
			"className":"com.caucho.network.listen.TcpSocketLink",
			"fileName":"TcpSocketLink.java",
			"lineNumber":1164,
			"methodName":"handleRequest",
			"nativeMethod":false
		},{
			"className":"com.caucho.network.listen.TcpSocketLink",
			"fileName":"TcpSocketLink.java",
			"lineNumber":1148,
			"methodName":"handleRequestsImpl",
			"nativeMethod":false
		},{
			"className":"com.caucho.network.listen.TcpSocketLink",
			"fileName":"TcpSocketLink.java",
			"lineNumber":1071,
			"methodName":"handleRequests",
			"nativeMethod":false
		},{
			"className":"com.caucho.network.listen.TcpSocketLink",
			"fileName":"TcpSocketLink.java",
			"lineNumber":907,
			"methodName":"handleAcceptTask",
			"nativeMethod":false
		},{
			"className":"com.caucho.network.listen.AcceptTask",
			"fileName":"AcceptTask.java",
			"lineNumber":74,
			"methodName":"doTask",
			"nativeMethod":false
		},{
			"className":"com.caucho.network.listen.ConnectionTask",
			"fileName":"ConnectionTask.java",
			"lineNumber":97,
			"methodName":"runThread",
			"nativeMethod":false
		},{
			"className":"com.caucho.network.listen.ConnectionTask",
			"fileName":"ConnectionTask.java",
			"lineNumber":80,
			"methodName":"run",
			"nativeMethod":false
		},{
			"className":"com.caucho.network.listen.AcceptTask",
			"fileName":"AcceptTask.java",
			"lineNumber":59,
			"methodName":"run",
			"nativeMethod":false
		},{
			"className":"com.caucho.env.thread.ResinThread",
			"fileName":"ResinThread.java",
			"lineNumber":164,
			"methodName":"runTasks",
			"nativeMethod":false
		},{
			"className":"com.caucho.env.thread.ResinThread",
			"fileName":"ResinThread.java",
			"lineNumber":130,
			"methodName":"run",
			"nativeMethod":false
		}],
		"suppressed":[]
	},
	"localizedMessage":"com.attilax.user.ex.UserExistEx: Duplicate entry '7' for key 'uni_uid' Query: insert agent(uid,pwd)values('7','111111')  Parameters: []",
	"message":"com.attilax.user.ex.UserExistEx: Duplicate entry '7' for key 'uni_uid' Query: insert agent(uid,pwd)values('7','111111')  Parameters: []",
	"stackTrace":[{
		"className":"com.attilax.exception.ExUtil",
		"fileName":"ExUtil.java",
		"lineNumber":58,
		"methodName":"throwExV2",
		"nativeMethod":false
	},{
		"className":"com.attilax.lang.Exprs",
		"fileName":"Exprs.java",
		"lineNumber":104,
		"methodName":"calc",
		"nativeMethod":false
	},{
		"className":"com.attilax.lang.AstParser",
		"fileName":"AstParser.java",
		"lineNumber":58,
		"methodName":"parseSingle",
		"nativeMethod":false
	},{
		"className":"com.attilax.lang.AstParser",
		"fileName":"AstParser.java",
		"lineNumber":49,
		"methodName":"parse",
		"nativeMethod":false
	},{
		"className":"com.attilax.wrmi.wrmiServletV3",
		"fileName":"wrmiServletV3.java",
		"lineNumber":157,
		"methodName":"service",
		"nativeMethod":false
	},{
		"className":"com.caucho.server.dispatch.ServletFilterChain",
		"fileName":"ServletFilterChain.java",
		"lineNumber":109,
		"methodName":"doFilter",
		"nativeMethod":false
	},{
		"className":"com.attilax.lang.exCatchor",
		"fileName":"exCatchor.java",
		"lineNumber":55,
		"methodName":"doFilter",
		"nativeMethod":false
	},{
		"className":"com.caucho.server.dispatch.FilterFilterChain",
		"fileName":"FilterFilterChain.java",
		"lineNumber":89,
		"methodName":"doFilter",
		"nativeMethod":false
	},{
		"className":"com.attilax.corePkg.ChineseCharFileUrlFilter",
		"fileName":"ChineseCharFileUrlFilter.java",
		"lineNumber":95,
		"methodName":"doFilter",
		"nativeMethod":false
	},{
		"className":"com.caucho.server.dispatch.FilterFilterChain",
		"fileName":"FilterFilterChain.java",
		"lineNumber":89,
		"methodName":"doFilter",
		"nativeMethod":false
	},{
		"className":"org.springframework.web.filter.CharacterEncodingFilter",
		"fileName":"CharacterEncodingFilter.java",
		"lineNumber":96,
		"methodName":"doFilterInternal",
		"nativeMethod":false
	},{
		"className":"org.springframework.web.filter.OncePerRequestFilter",
		"fileName":"OncePerRequestFilter.java",
		"lineNumber":76,
		"methodName":"doFilter",
		"nativeMethod":false
	},{
		"className":"com.caucho.server.dispatch.FilterFilterChain",
		"fileName":"FilterFilterChain.java",
		"lineNumber":89,
		"methodName":"doFilter",
		"nativeMethod":false
	},{
		"className":"com.caucho.server.webapp.WebAppFilterChain",
		"fileName":"WebAppFilterChain.java",
		"lineNumber":156,
		"methodName":"doFilter",
		"nativeMethod":false
	},{
		"className":"com.caucho.server.webapp.AccessLogFilterChain",
		"fileName":"AccessLogFilterChain.java",
		"lineNumber":95,
		"methodName":"doFilter",
		"nativeMethod":false
	},{
		"className":"com.caucho.server.dispatch.ServletInvocation",
		"fileName":"ServletInvocation.java",
		"lineNumber":289,
		"methodName":"service",
		"nativeMethod":false
	},{
		"className":"com.caucho.server.http.HttpRequest",
		"fileName":"HttpRequest.java",
		"lineNumber":811,
		"methodName":"handleRequest",
		"nativeMethod":false
	},{
		"className":"com.caucho.network.listen.TcpSocketLink",
		"fileName":"TcpSocketLink.java",
		"lineNumber":1203,
		"methodName":"dispatchRequest",
		"nativeMethod":false
	},{
		"className":"com.caucho.network.listen.TcpSocketLink",
		"fileName":"TcpSocketLink.java",
		"lineNumber":1164,
		"methodName":"handleRequest",
		"nativeMethod":false
	},{
		"className":"com.caucho.network.listen.TcpSocketLink",
		"fileName":"TcpSocketLink.java",
		"lineNumber":1148,
		"methodName":"handleRequestsImpl",
		"nativeMethod":false
	},{
		"className":"com.caucho.network.listen.TcpSocketLink",
		"fileName":"TcpSocketLink.java",
		"lineNumber":1071,
		"methodName":"handleRequests",
		"nativeMethod":false
	},{
		"className":"com.caucho.network.listen.TcpSocketLink",
		"fileName":"TcpSocketLink.java",
		"lineNumber":907,
		"methodName":"handleAcceptTask",
		"nativeMethod":false
	},{
		"className":"com.caucho.network.listen.AcceptTask",
		"fileName":"AcceptTask.java",
		"lineNumber":74,
		"methodName":"doTask",
		"nativeMethod":false
	},{
		"className":"com.caucho.network.listen.ConnectionTask",
		"fileName":"ConnectionTask.java",
		"lineNumber":97,
		"methodName":"runThread",
		"nativeMethod":false
	},{
		"className":"com.caucho.network.listen.ConnectionTask",
		"fileName":"ConnectionTask.java",
		"lineNumber":80,
		"methodName":"run",
		"nativeMethod":false
	},{
		"className":"com.caucho.network.listen.AcceptTask",
		"fileName":"AcceptTask.java",
		"lineNumber":59,
		"methodName":"run",
		"nativeMethod":false
	},{
		"className":"com.caucho.env.thread.ResinThread",
		"fileName":"ResinThread.java",
		"lineNumber":164,
		"methodName":"runTasks",
		"nativeMethod":false
	},{
		"className":"com.caucho.env.thread.ResinThread",
		"fileName":"ResinThread.java",
		"lineNumber":130,
		"methodName":"run",
		"nativeMethod":false
	}],
	"suppressed":[]
};

